Repository ipt-cryptolabs/fb-labs-2021, pull requests merged in 2021-11, with the labels that each got.

#47 [CP-3] Nosova (FB-91), Snigur (FB-91)
  cp_3/Nosova_fb-91_Snigur_fb-91/main.py
  cp_3/Nosova_fb-91_Snigur_fb-91/Міністерство освіти і науки України.pdf
Labels: needs_cleanup, report_improvements

#16 [CP-1] Bratunets (FB-91)
  cp_1/Bratunets_fb-91_cp1/main.py
  cp_1/Bratunets_fb-91_cp1/text2.txt
  cp_1/Bratunets_fb-91_cp1/Практикум№1.pdf
Labels: needs_cleanup

#49 [CP-2] Pashinskiy (FB-91)
  cp_2/pashinskiy_fb-91_cp2/crypt2.cpp
  cp_2/pashinskiy_fb-91_cp2/protocol.pdf
  cp_2/pashinskiy_fb-91_cp2/text.txt
  cp_2/pashinskiy_fb-91_cp2/variant.TXT
Labels: needs_cleanup

#51 [CP-3] Osmak_Legenchuk (FB-91)
  cp_3/osmak_legenchuk_fb-91_cp_3/code.cpp
  cp_3/osmak_legenchuk_fb-91_cp_3/Криптографія_лр3.pdf
Labels: code_improvements

#54 [CP-3] Bratunets (FB-91)
  cp_3/Bratunets_fb-91_cp3/02.txt
  cp_3/Bratunets_fb-91_cp3/decrypted.txt
  cp_3/Bratunets_fb-91_cp3/main.py
  cp_3/Bratunets_fb-91_cp3/Практикум3протокол.pdf
Labels: bad_results
