Repository ipt-cryptolabs/fb-labs-2021, pull requests merged in 2021-12, with the labels that each got.

#71 [CP-4] Melnyk (FB-91), Tyslytskyi (FB-91)
  cp_4/melnyk_fb-91_tyslytskyi_fb-91_cp4/math_functions.py
  cp_4/melnyk_fb-91_tyslytskyi_fb-91_cp4/result.txt
  cp_4/melnyk_fb-91_tyslytskyi_fb-91_cp4/rsa.py
  cp_4/melnyk_fb-91_tyslytskyi_fb-91_cp4/test_numbers.txt
  cp_4/melnyk_fb-91_tyslytskyi_fb-91_cp4/КП4_Мельник_Тислицький_ФБ-91.pdf
Labels: key_exchange_example

#74 [CP-4] Bratunets (FB-91)
  cp_4/Bratunets_fb-91_cp4/testMillRab.py
  cp_4/Bratunets_fb-91_cp4/ПротоколЛаб4.pdf
Labels: key_exchange_example

#73 [CP-4] Zhurybeda (FB-91)
  cp_4/zhurybeda_fb-91_cp_4/cryptolab4.pdf
  cp_4/zhurybeda_fb-91_cp_4/lab4.py
Labels: bad_directory, key_exchange_example

#78 [CP-4] Podus (FB-91)
  cp_4/podus_fb-91_cp4/main.py
  cp_4/podus_fb-91_cp4/Протокол Лабораторна робота №4.pdf
Labels: code_improvements

#33 [CP-2] Shvets fb-91
  cp_2/shvets_fb-91_cp2/encrypted
  cp_2/shvets_fb-91_cp2/key_ИНДЕКСАЦИЯ.txt
  cp_2/shvets_fb-91_cp2/key_КАША.txt
  cp_2/shvets_fb-91_cp2/key_МАЗУТ.txt
  cp_2/shvets_fb-91_cp2/key_МЫ.txt
  cp_2/shvets_fb-91_cp2/key_ПЕС.txt
  cp_2/shvets_fb-91_cp2/key_РЫБА.txt
  cp_2/shvets_fb-91_cp2/main.py
  cp_2/shvets_fb-91_cp2/text.txt
  cp_2/shvets_fb-91_cp2/протокол_варіант_2.pdf
Labels: needs_cleanup

#12 [CP-1] Shvets (FB-91)
  cp_1/shvets_cp_1_fb_91/main.py
  cp_1/shvets_cp_1_fb_91/shvets_fb-91_cp1.pdf
Labels: bad_directory, bad_results, needs_cleanup

#56 [CP-3] M. Shvets (FB-91)
  cp_1/mshvets/Снимок экрана 2021-09-27 134143.png
  cp_3/shvets_fb-91_cp_3/main.py
  cp_3/shvets_fb-91_cp_3/shvets_fb-91_cp3.pdf
  cp_3/shvets_fb_91_cp3/main.py
  cp_3/shvets_fb_91_cp3/shvets_fb-91_cp3.pdf
Labels: needs_cleanup

#70 [CP-4] Kuzavka (FB-91)
  cp_4/kuzavka_fb_91_cp4/A.dec
  cp_4/kuzavka_fb_91_cp4/A.enc
  cp_4/kuzavka_fb_91_cp4/A_ciphertext.txt
  cp_4/kuzavka_fb_91_cp4/Miller-Rabin.py
  cp_4/kuzavka_fb_91_cp4/RSA.py
  cp_4/kuzavka_fb_91_cp4/protocol.pdf
Labels: code_improvements, key_exchange_example
